project_id = "mbhjganbihamoiqmankv"

[functions.webrtc-signaling]
verify_jwt = false

[functions.live-stream-signaling]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.ai-generate-image]
verify_jwt = false
